name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Set up Git identity and push changes
      env:
        GH_TOKEN: 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
      run: |
        git config user.email "thiendong.iuh@gmail.com"
        git config user.name "dongtran"
        git pull origin main

    - name: Install dependencies and create package-lock.json
      run: |
        npm install
        npm install grunt --save-dev
        npm install grunt-contrib-copy grunt-bump grunt-exec --save-dev
        grunt
