name: NodeJS with Grunt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 14.x
      uses: actions/setup-node@v3
      with:
        node-version: 14.x  # Sử dụng phiên bản Node.js 14.x

    # Các bước tiếp theo tương tự như trước đó...
    - name: Set up Git identity and push changes
      env:
        GH_TOKEN: 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
        NODE_AUTH_TOKEN: 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
      run: |
        git config user.email "thiendong.iuh@gmail.com"
        git config user.name "dongtran"
        git pull origin main

    - name: Install dependencies and create package-lock.json
      run: |
        npm install
        npm install grunt --save-dev
        npm install grunt-contrib-copy grunt-bump grunt-exec --save-dev
        grunt
    